package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

const schema = `
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS bank (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bank_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS eps_vendor_info (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	biz_reg_no TEXT NOT NULL UNIQUE,
	vendor_name TEXT NOT NULL,
	contact TEXT NOT NULL DEFAULT '',
	password TEXT NOT NULL,
	bank_id INTEGER REFERENCES bank(id) ON UPDATE CASCADE,
	account_no TEXT NOT NULL DEFAULT '',
	account_holder TEXT NOT NULL DEFAULT '',
	biz_reg_cert TEXT NOT NULL DEFAULT '',
	bank_account_copy TEXT NOT NULL DEFAULT '',
	check_discard BOOLEAN NOT NULL DEFAULT false,
	date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS eps_vendor_manager_info (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vendor_id INTEGER NOT NULL REFERENCES eps_vendor_info(id) ON DELETE CASCADE ON UPDATE CASCADE,
	is_main BOOLEAN NOT NULL DEFAULT false,
	manager_name TEXT NOT NULL,
	position TEXT NOT NULL DEFAULT '',
	department TEXT NOT NULL DEFAULT '',
	contact_mobile TEXT NOT NULL DEFAULT '',
	contact_direct TEXT NOT NULL DEFAULT '',
	email TEXT NOT NULL DEFAULT '',
	notification TEXT NOT NULL DEFAULT '',
	check_discard BOOLEAN NOT NULL DEFAULT false,
	date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
	date_updated TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS eps_vendor_manager_info_one_main_per_vendor_idx
	ON eps_vendor_manager_info (vendor_id)
	WHERE is_main = true AND check_discard = false;

CREATE UNIQUE INDEX IF NOT EXISTS eps_vendor_manager_info_active_email_idx
	ON eps_vendor_manager_info (lower(email))
	WHERE email <> '' AND check_discard = false;

CREATE TABLE IF NOT EXISTS unit (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	unit TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS supplier (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vendor_id INTEGER REFERENCES eps_vendor_info(id) ON DELETE SET NULL ON UPDATE CASCADE,
	supplier_name TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS supplier_vendor_id_idx ON supplier(vendor_id);

CREATE TABLE IF NOT EXISTS eps_estimate_request (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bid BOOLEAN NOT NULL DEFAULT false,
	date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
	date_discard TIMESTAMPTZ,
	product_name TEXT NOT NULL,
	cas_no TEXT NOT NULL DEFAULT '',
	supplier_id INTEGER REFERENCES supplier(id) ON DELETE SET NULL ON UPDATE CASCADE,
	catalog_no TEXT NOT NULL DEFAULT '',
	unit_value DOUBLE PRECISION NOT NULL DEFAULT 0,
	unit INTEGER REFERENCES unit(id) ON DELETE SET NULL ON UPDATE CASCADE,
	count INTEGER NOT NULL DEFAULT 1 CHECK (count > 0),
	status TEXT,
	purchase_request INTEGER,
	note TEXT NOT NULL DEFAULT '',
	discard BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS eps_estimate_request_status_idx ON eps_estimate_request(status);
CREATE INDEX IF NOT EXISTS eps_estimate_request_supplier_id_idx ON eps_estimate_request(supplier_id);
CREATE INDEX IF NOT EXISTS eps_estimate_request_unit_idx ON eps_estimate_request(unit);

CREATE OR REPLACE FUNCTION estimate_request_json(r eps_estimate_request)
RETURNS json
LANGUAGE sql
STABLE
AS $$
	SELECT json_build_object(
		'id', r.id,
		'bid', r.bid,
		'dateCreated', r.date_created,
		'dateDiscard', r.date_discard,
		'productName', r.product_name,
		'casNo', r.cas_no,
		'supplierId', r.supplier_id,
		'catalogNo', r.catalog_no,
		'unitValue', r.unit_value,
		'unitId', r.unit,
		'unit', (SELECT u.unit FROM unit u WHERE u.id = r.unit),
		'count', r.count,
		'status', r.status,
		'purchaseRequest', r.purchase_request,
		'note', r.note,
		'discard', r.discard
	);
$$;

CREATE TABLE IF NOT EXISTS eps_estimate_response (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_id INTEGER NOT NULL REFERENCES eps_estimate_request(id) ON DELETE CASCADE ON UPDATE CASCADE,
	vendor_id INTEGER NOT NULL REFERENCES eps_vendor_info(id) ON DELETE CASCADE ON UPDATE CASCADE,
	vendor_name TEXT NOT NULL DEFAULT '',
	product_name TEXT NOT NULL,
	supplier_id INTEGER REFERENCES supplier(id) ON DELETE SET NULL ON UPDATE CASCADE,
	catalog_no TEXT NOT NULL DEFAULT '',
	unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
	unit_value DOUBLE PRECISION NOT NULL DEFAULT 0,
	unit INTEGER REFERENCES unit(id) ON DELETE SET NULL ON UPDATE CASCADE,
	count INTEGER NOT NULL DEFAULT 1 CHECK (count > 0),
	delivery_period TEXT NOT NULL DEFAULT '',
	total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
	document_path TEXT NOT NULL DEFAULT '',
	discard BOOLEAN NOT NULL DEFAULT false,
	date_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
	date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS eps_estimate_response_request_id_idx ON eps_estimate_response(request_id);
CREATE INDEX IF NOT EXISTS eps_estimate_response_vendor_id_idx ON eps_estimate_response(vendor_id);
CREATE INDEX IF NOT EXISTS eps_estimate_response_supplier_id_idx ON eps_estimate_response(supplier_id);
CREATE INDEX IF NOT EXISTS eps_estimate_response_unit_idx ON eps_estimate_response(unit);

CREATE TABLE IF NOT EXISTS eps_order (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	response_id INTEGER UNIQUE REFERENCES eps_estimate_response(id) ON DELETE SET NULL ON UPDATE CASCADE,
	shipment TIMESTAMPTZ,
	received TIMESTAMPTZ,
	is_paid BOOLEAN NOT NULL DEFAULT false,
	date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
	discard BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS require_list (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	plot TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS require (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	require_list_id INTEGER NOT NULL REFERENCES require_list(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	vendor_id INTEGER NOT NULL REFERENCES eps_vendor_info(id) ON DELETE CASCADE ON UPDATE CASCADE,
	estimate_request_id INTEGER NOT NULL REFERENCES eps_estimate_request(id) ON DELETE CASCADE ON UPDATE CASCADE,
	comment TEXT NOT NULL DEFAULT '',
	date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS require_require_list_id_idx ON require(require_list_id);
CREATE INDEX IF NOT EXISTS require_vendor_id_idx ON require(vendor_id);
CREATE INDEX IF NOT EXISTS require_estimate_request_id_idx ON require(estimate_request_id);

CREATE TABLE IF NOT EXISTS ips2eps_request (
	eps_id INTEGER NOT NULL REFERENCES eps_estimate_request(id) ON DELETE CASCADE ON UPDATE CASCADE,
	ips_id INTEGER NOT NULL,
	PRIMARY KEY (eps_id, ips_id)
);

CREATE TABLE IF NOT EXISTS ips2eps_response (
	eps_id INTEGER NOT NULL REFERENCES eps_estimate_response(id) ON DELETE CASCADE ON UPDATE CASCADE,
	ips_id INTEGER NOT NULL,
	PRIMARY KEY (eps_id, ips_id)
);

CREATE TABLE IF NOT EXISTS ips2eps_order (
	eps_id INTEGER NOT NULL REFERENCES eps_order(id) ON DELETE CASCADE ON UPDATE CASCADE,
	ips_id INTEGER NOT NULL,
	PRIMARY KEY (eps_id, ips_id)
);

CREATE INDEX IF NOT EXISTS ips2eps_request_ips_id_idx ON ips2eps_request(ips_id);
CREATE INDEX IF NOT EXISTS ips2eps_response_ips_id_idx ON ips2eps_response(ips_id);
CREATE INDEX IF NOT EXISTS ips2eps_order_ips_id_idx ON ips2eps_order(ips_id);
`

func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	_, err := pool.Exec(ctx, schema)
	return err
}
